apiVersion: v1
kind: PersistentVolume
metadata:
  name: topomojo-nfs-1
spec:
  storageClassName: 'nfs'
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    server: FS-01.ramrod.io
    path: '$TOPOMJO_ISOSTORE'
