apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topomojo
spec:
  storageClassName: nfs
  resources:
    requests:
      storage: 5Ti
  accessModes:
    - ReadWriteOnce
  volumeName: topomojo-nfs-1
