# Default values for gitea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

clusterDomain: cluster.local

image:
  repository: gitea/gitea
  version: 1.14.3
  pullPolicy: Always

imagePullSecrets: []

service:
  http:
    type: ClusterIP
    port: 3000
  ssh:
    type: ClusterIP
    port: 22
    #loadBalancerIP:
    #nodePort:
    #externalTrafficPolicy:
    #externalIPs:
    annotations:

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: foundry.local
      paths:
        - path: "/gitea(/|$)(.*)"
          pathType: Prefix
  tls:
    - secretName: appliance-cert
      hosts:
        - foundry.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

statefulset:
  env: []
    # - name: VARIABLE
    #   value: my-value
  terminationGracePeriodSeconds: 60

persistence:
  enabled: true
  # existingClaim:
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClass: microk8s-hostpath

gitea:
  admin:
    username: administrator
    password: foundry
    email: "administrator@foundry.local"

  ldap:
    enabled: false
    name: ""
    securityProtocol: ""
    host: ""
    port: ""
    userSearchBase: ""
    userFilter: ""
    adminFilter: ""
    emailAttribute: ""
    bindDn: ""
    bindPassword: ""
    usernameAttribute: ""

  config:
    APP_NAME: Foundry Gitea
    server:
      DOMAIN: https://foundry.local/gitea/
      ROOT_URL: https://foundry.local/gitea/
    security:
      PASSWORD_COMPLEXITY: "off"

  podAnnotations: {}

  database:
    builtIn:
      postgresql:
        enabled: true
      mysql:
        enabled: false
      mariadb:
        enabled: false

  cache:
    builtIn:
      enabled: true

memcached:
  service:
    port: 11211

postgresql:
  global:
    postgresql:
      postgresqlDatabase: gitea
      postgresqlUsername: gitea
      postgresqlPassword: gitea
      servicePort: 5432
  persistence:
    size: 1Gi

mysql:
  root:
    password: gitea
  db:
    user: gitea
    password: gitea
    name: gitea
  service:
    port: 3306
  persistence:
    size: 10Gi

mariadb:
  auth:
    database: gitea
    username: gitea
    password: gitea
    rootPassword: gitea
  primary:
    service:
      port: 3306
    persistence:
      size: 10Gi
