apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mattermost-team-edition.fullname" . }}-entry
  labels:
    app.kubernetes.io/name: {{ include "mattermost-team-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-team-edition.chart" . }}

data:
  entryscript: |
{{ .Values.entryscript | indent 4 }}
