alloy-api:
  image: 
    repository: cmusei/alloy-api
    tag: '3.2.3'
    pullPolicy: Always
  command: ["bash", "-c", "update-ca-certificates && dotnet Alloy.Api.dll"]

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: $INGRESS_CLASS
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: 'true'
    hosts:
      - host: $DOMAIN
        paths:
          - path:  /alloy/(hubs|api|swagger)
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
          - $DOMAIN
  
  # If this deployment needs to trust non-public certificates,
  # create a configMap with the needed certifcates and specify
  # the configMap name here
  certificateMap: "appliance-root-ca"
  
  identity:
    register: true
    identityMap: "identity-identity-api"
    #initCommand: ['sh', '-c', 'sleep 10000']
    client: |-
      [
        {
          "name": "alloy-api",
          "displayName": "Alloy API",
          "description": null,
          "grants": "authorization_code client_credentials",
          "scopes": "alloy-api player-api vm-api caster-api steamfitter-api",
          "enabled": true,
          "requirePkce": true,
          "allowAccessTokensViaBrowser": false,
          "requireConsent": false,
          "consentLifetime": "30d",
          "alwaysIncludeUserClaimsInIdToken": false,
          "identityTokenLifetime": "5m",
          "accessTokenLifetime": "1h",
          "authorizationCodeLifetime": "5m",
          "allowOfflineAccess": false,
          "updateAccessTokenClaimsOnRefresh": false,
          "useOneTimeRefreshTokens": false,
          "slidingRefreshTokenLifetime": "15d",
          "absoluteRefreshTokenLifetime": "30d",
          "published": false,
          "url": "https://$DOMAIN/alloy",
          "logoUrl": null,
          "frontChannelLogoutUrl": null,
          "backChannelLogoutUrl": null,
          "redirectUrls": [
            { "value": "https://$DOMAIN/alloy/api/oauth2-redirect.html" }
          ],
          "postLogoutUrls": [{ "value": "https://$DOMAIN/alloy/api" }],
          "corsUrls": [{ "value": "https://$DOMAIN" }],
          "alwaysSendClientClaims": false,
          "clientClaimsPrefix": "client_",
          "claims": [],
          "secrets": [],
          "managers": []
        },
        {
          "name": "alloy-admin",
          "displayName": "Alloy Admin",
          "description": null,
          "grants": "password client_credentials",
          "scopes": "alloy-api player-api caster-api steamfitter-api vm-api",
          "enabled": true,
          "requirePkce": true,
          "allowAccessTokensViaBrowser": false,
          "requireConsent": false,
          "consentLifetime": "30d",
          "alwaysIncludeUserClaimsInIdToken": false,
          "identityTokenLifetime": "5m",
          "accessTokenLifetime": "1h",
          "authorizationCodeLifetime": "5m",
          "allowOfflineAccess": false,
          "updateAccessTokenClaimsOnRefresh": false,
          "useOneTimeRefreshTokens": false,
          "slidingRefreshTokenLifetime": "15d",
          "absoluteRefreshTokenLifetime": "30d",
          "published": false,
          "url": "https://$DOMAIN/alloy",
          "logoUrl": null,
          "frontChannelLogoutUrl": null,
          "backChannelLogoutUrl": null,
          "corsUrls": [{ "value": "https://$DOMAIN" }],
          "alwaysSendClientClaims": false,
          "clientClaimsPrefix": "client_",
          "claims": [],
          "secrets": [],
          "managers": []
        }
      ]
    resource: |-
      {
        "type": "api",
        "name": "alloy-api",
        "displayName": "Alloy Api",
        "enabled": true,
        "default": true,
        "required": false,
        "emphasize": false,
        "showInDiscoveryDocument": true
      }

    account: |-
      {
        "usernames": ["alloy-admin@$DOMAIN"],
        "password": "foundry",
        "manager": true
      }
  
  env:
    PathBase: "/alloy"
    CorsPolicy__Origins__0: https://$DOMAIN
    CorsPolicy__AllowAnyMethod: true
    CorsPolicy__AllowAnyHeader: true
    Logging__LogLevel__Default: "debug"
    # Connection String to database
    ConnectionStrings__PostgreSQL: "Server=$POSTGRES_SERVER;Port=5432;Database=alloy_db;Username=$POSTGRES_USER;Password='$POSTGRES_PASS';SSL Mode=Prefer;Trust Server Certificate=true;"

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://$DOMAIN/identity
    Authorization__AuthorizationUrl: https://$DOMAIN/identity/connect/authorize
    Authorization__TokenUrl: https://$DOMAIN/identity/connect/token
    Authorization__AuthorizationScope: 'alloy-api caster-api steamfitter-api vm-api'
    Authorization__ClientId: alloy-api
    Authorization__ClientName: 'Alloy API'

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://$DOMAIN/identity
    ResourceOwnerAuthorization__ClientId: alloy-admin
    ResourceOwnerAuthorization__UserName: player-admin@$DOMAIN # TODO
    ResourceOwnerAuthorization__Password: $ADMIN_PASS # TODO
    ResourceOwnerAuthorization__Scope: 'alloy-api player-api caster-api steamfitter-api vm-api'

    # Crucible Application URLs
    ClientSettings__urls__playerApi: https://$DOMAIN/player
    ClientSettings__urls__casterApi: https://$DOMAIN/caster
    ClientSettings__urls__steamfitterApi: https://$DOMAIN/steamfitter

alloy-ui:
  image:
    repository: cmusei/alloy-ui
    pullPolicy: IfNotPresent
    tag: '3.2.3'

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: $INGRESS_CLASS
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: $DOMAIN
        paths:
          - path: "/alloy(/|$)(.*)"
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
          - $DOMAIN


  identity:
    register: true
    identityMap: "identity-identity-api"
    client: |-
      {
        "name": "alloy-ui",
        "displayName": "Alloy UI",
        "description": null,
        "grants": "authorization_code client_credentials",
        "scopes": "openid profile alloy-api player-api caster-api steamfitter-api vm-api",
        "enabled": true,
        "requirePkce": true,
        "allowAccessTokensViaBrowser": true,
        "requireConsent": false,
        "consentLifetime": "30d",
        "alwaysIncludeUserClaimsInIdToken": false,
        "identityTokenLifetime": "5m",
        "accessTokenLifetime": "1h",
        "authorizationCodeLifetime": "5m",
        "allowOfflineAccess": false,
        "updateAccessTokenClaimsOnRefresh": false,
        "useOneTimeRefreshTokens": false,
        "slidingRefreshTokenLifetime": "15d",
        "absoluteRefreshTokenLifetime": "30d",
        "published": true,
        "url": "https://$DOMAIN/alloy/",
        "logoUrl": null,
        "frontChannelLogoutUrl": null,
        "backChannelLogoutUrl": null,
        "redirectUrls": [
          { "value": "https://$DOMAIN/alloy/auth-callback" },
          { "value": "https://$DOMAIN/alloy/auth-callback-silent" }
        ],
        "postLogoutUrls": [{ "value": "https://$DOMAIN/alloy" }],
        "corsUrls": [{ "value": "https://$DOMAIN" }],
        "alwaysSendClientClaims": false,
        "clientClaimsPrefix": "client_",
        "claims": [],
        "secrets": [],
        "managers": []
      }
  env: 
    ## basehref is path to the app
    APP_BASEHREF: "/alloy"

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client and
  # some basic configuration
  # NOTE:  PlayerUIAddress is the URL to the Crucible - Player application
  settings: |-
    {
      "ApiUrl": "https://$DOMAIN/alloy",
      "OIDCSettings": {
        "authority": "https://$DOMAIN/identity/",
        "client_id": "alloy-ui",
        "redirect_uri": "https://$DOMAIN/alloy/auth-callback",
        "post_logout_redirect_uri": "https://$DOMAIN/alloy",
        "response_type": "code",
        "scope": "openid profile alloy-api player-api caster-api steamfitter-api vm-api",
        "automaticSilentRenew": true,
        "silent_redirect_uri": "https://$DOMAIN/alloy/auth-callback-silent"
      },
      "AppTitle": "Alloy",
      "AppTopBarText": "Alloy",
      "AppTopBarHexColor": "#b00",
      "PlayerUIAddress": "https://$DOMAIN/player",
      "UseLocalAuthStorage": true
    }
