image:
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: $INGRESS_CLASS
  tls:
    - secretName: appliance-cert
      hosts:
        - $DOMAIN

st2web:
  service:
    hostname: $DOMAIN/stackstorm

enterprise:
  enabled: false

mongodb-ha:
  enabled: true
  image:
  serviceAccount: stackstorm-mongodb-ha
  auth:
    enabled: true
    adminUser: 'mongo'
    adminPassword: '$ADMIN_PASS'
    key: '$STACKSTORM_MONGO_KEY'
  persistentVolume:
    enabled: false

rabbitmq-ha:
  enabled: true
  rabbitmqUsername: administrator
  rabbitmqPassword: '$ADMIN_PASS'
  persistentVolume:
    enabled: false

st2:
  # Username, used to login to StackStorm system
  username: administrator
  # Password, used to login to StackStorm system
  password: '$ADMIN_PASS'
  packs:
    configs:
      # TODO -- Fill this out to make the Azure Pack work
      # https://github.com/StackStorm-Exchange/stackstorm-azure
      azure.yaml: |
        ---
        compute:
          subscription_id: "$AZURE_COMPUTE_SUBSCRIPTION_ID"
          cert_file: "$AZURE_COMPUTE_CERT_FILE"
        storage:
          name: "$AZURE_STORAGE_NAME"
          access_key: "$AZURE_STORAGE_ACCESS_KEY"
        resource_manager:
          client_id: '$AZURE_RESOURCE_CLIENT_ID'
          secret: '$AZURE_RESOURCE_SECRET'
          tenant: '$AZURE_RESOURCE_TENANT'
          default_resource_group: '$AZURE_RESOURCE_DEFAULT_GROUP'
        user:
          username: '$AZURE_USER'
          password: '$AZURE_PASS'

    # StackStorm HA mounts non-core packs via a sidecar installation
    # This image is custom-built to contain the vSphere and Azure Pack
    # NOTE:  The tag version represents the Azure Pack version number
    images: 
      - repository: cmusei
        name: st2packs
        tag: azure-0.4.3-python3
        pullPolicy: IfNotPresent
        
    # Provide a default name for the sensor
    sensors:
      - name: stackstorm-sensor
        serviceAccount:
          attach: false